language: python
python:
  - '3.5'
  - '3.4'
  - '2.7'

install: pip install .

before_script:
  - cd tests/
  - echo "https://gate.angus.ai" >> config_input.txt
  - echo "$CLIENT_ID" >> config_input.txt
  - echo "$ACCESS_TOKEN" >> config_input.txt
  - angusme < config_input.txt
  - cat ~/.angusdk/config.json

script: py.test --root=https://gate.angus.ai --client_id=$CLIENT_ID --access_token=$ACCESS_TOKEN

env:
  global:
  - secure: iYi/2GWXf9q6LLFTjABE0jA/KNfjFwEbnAMGGGwOjZE/qTTcTOxC0+Wq5gUJklKj22N7xzlcq8VuVqGmChKS5Z4ErOnFQ2Ei8GW43lZtHyDyV9gCM90jWBBDaWLQlekvKsIphoNn7ZpHNx4lGAsSHjWC7dMZMNeq8Hp4wJJk7CA=
  - secure: XmpPU6mpDN67s/EKXCOol5rgtGbW77szX4yFBNypcm5lQZmFdYApuycdM24vVgeQPLx5nLlG9ZJm7SGh0bwiMGas/3y4xHMCWzneeEDDjjkeYodX0AHkhFBXrMdFG/3JgMxu4uBKb52/Jo7K19B6USCresQNOwOP9vUok722JSk=
