language: python
python:
  - '3.5'
  - '3.4'
  - '2.7'

install: pip install .

before_script:
  - cd tests/
  - echo "https://gate.angus.ai" >> config_input.txt
  - echo "$CLIENT_ID" >> config_input.txt
  - echo "$ACCESS_TOKEN" >> config_input.txt
  - angusme < config_input.txt

script: py.test --root=https://gate.angus.ai --client_id=$CLIENT_ID --access_token=$ACCESS_TOKEN

env:
  global:
  - secure: AGO2UX6bXeQLy1QMEJTv3EykOBHAARyeiWbGZgbiwmNcHgKN7uSza+SvnNQAzC7kJVmBOAhbuC1j5q2VtrBN1qPIUzprTkucPaE/ozYHqcsvM5qeiqqzT6DavA9PB+wmo//aspv6qd9wlf1fNx+eovClMUDt/dQTDPInlUVI5Ew=
  - secure: eRE2kfMcaKtsiuxSGoN4HtvYghqY4iAj/vlOims8KD1UaKi0twN5EdywPpSixz7hR7W4x05dHTkFLgN+mzBy10LBfxSaWdt3M4nfwn5GlG1qmssnPpYEKGJQy5x9QJtnLpcx4tXoNSdX1VKg16NZzXS7k4CywsyZXxpbfoKsWMQ=
